version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  test:
    executor:
      name: node/default
      tag: "16.10"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Unit Tests
          command: npm run test:unit
workflows:
  run_tests:
    jobs:
      - test
