version: 2.1
orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    executor:
      name: node/default
      tag: "16.10"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Unit Tests
          command: npm run test:unit
workflows:
  build-and-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          api-key: HEROKU_API_KEY
          app-name: babbling-brook
          branch: develop

