version: 2.1
orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    executor:
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages
      # - run:
      #     name: Install JUnit Coverage Reporter
      #     command: npm i -D jest-junit
      # - run:
      #     name: Run Unit Tests with Coverage
      #     command: npm run test:unit -- --ci --runInBand --reporters=default --reporters=jest-junit
      #     environment:
      #       JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      # - store_test_results:
      #     path: ./reports/junit/
      # - store_artifacts:
      #     path: ./reports/junit/
workflows:
  build-and-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          api-key: HEROKU_API_KEY
          app-name: babbling-brook
          branch: develop
